### PR TITLE
typo: correct org.springframework.ai to org.springframework.grpc

### PR DESCRIPTION
**Pull request by linux-china**

### CODE REVIEW

**Comment by onobc** [comment]
Hi @linux-china 
I just realized this PR is the same as the one that I just merged https://github.com/spring-projects-experimental/spring-grpc/pull/39. You made the fix first and I should have merged yours but I just noticed as I working the PRs top-down. 
Thank you for the fix.

**Comment by onobc** [comment]
Closing via https://github.com/spring-projects-experimental/spring-grpc/pull/39

**Comment by lbkulinski** [comment]
@onobc I did see this PR, but it didn't fix all occurrences of the group ID typo from what I could see. I figured it would just be easier to open a separate PR to fix both occurrences

**Comment by onobc** [comment]
I just want you to know that we appreciate your contributions @lbkulinski and it was my bad as your PR was actually the first one submitted. It happens sometimes though 😄. 

Thank you.

**Pull request closed without merging**
